version: 2

multi-ecosystem-groups:
  monthly-maintenance:
    schedule:
      interval: "monthly"

updates:
  - package-ecosystem: "pip"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "monthly-maintenance"
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - maintenance

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "monthly-maintenance"
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - maintenance
