"""Offline Trap Lab artifacts for memorable, zero-API report bundles."""

from __future__ import annotations

import csv
import io
import json
from datetime import datetime, timezone
from pathlib import Path

from .inquiry import write_inquiry_artifacts
from .proof_surfaces import build_offline_proof_pdf, build_proof_dossier_html, build_ui_mockup_html
from .specimens import build_specimen_codex


def _survived(event: dict) -> bool:
    severity = str(event.get("severity", "low")).lower()
    return int(event.get("proven_count", 0)) == 0 and severity not in {"high", "critical"}


def _prompt_excerpt(prompt: str, limit: int = 96) -> str:
    value = " ".join(prompt.split())
    if len(value) <= limit:
        return value
    return value[: limit - 3] + "..."


def build_trap_ledger(report: dict) -> list[dict]:
    """Return a row-oriented trap ledger for CSV/JSON use."""
    rows = []
    for index, event in enumerate(report.get("events", []), start=1):
        specimen_names = []
        attack_families = []
        for finding in event.get("findings", []):
            attack_family = str(finding.get("attack_family", "unknown"))
            attack_families.append(attack_family)
        codex = build_specimen_codex({"events": [event]})
        for specimen in codex.get("specimens", []):
            if int(specimen.get("sightings", 0)) > 0:
                specimen_names.append(str(specimen.get("name", "Unknown Specimen")))
        rows.append(
            {
                "trap": index,
                "survived": "yes" if _survived(event) else "no",
                "severity": str(event.get("severity", "low")),
                "risk_score": int(event.get("risk_score", 0)),
                "finding_count": int(event.get("finding_count", 0)),
                "proven_count": int(event.get("proven_count", 0)),
                "specimens": "; ".join(specimen_names),
                "attack_families": "; ".join(dict.fromkeys(attack_families)),
                "prompt_excerpt": _prompt_excerpt(str(event.get("prompt", ""))),
            }
        )
    return rows


def build_trap_ledger_csv(report: dict) -> str:
    rows = build_trap_ledger(report)
    output = io.StringIO()
    fieldnames = [
        "trap",
        "survived",
        "severity",
        "risk_score",
        "finding_count",
        "proven_count",
        "specimens",
        "attack_families",
        "prompt_excerpt",
    ]
    writer = csv.DictWriter(output, fieldnames=fieldnames, lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()


def build_field_guide_markdown(report: dict, *, source_label: str, title: str) -> str:
    codex = build_specimen_codex(report)
    rows = build_trap_ledger(report)
    total = len(rows)
    survived = sum(1 for row in rows if row["survived"] == "yes")
    bitten = total - survived
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# {title} Field Guide",
        "",
        "This is an offline Trap Lab notebook generated by Honeypot Med.",
        "No hosted service, model API, or paid dependency is required to create this artifact.",
        "",
        "## Lab Stamp",
        "",
        f"- Source: {source_label}",
        f"- Generated: {generated}",
        f"- Traps observed: {total}",
        f"- Traps survived: {survived}",
        f"- Proven bites: {bitten}",
        "",
        "## Specimen Codex",
        "",
    ]
    for specimen in codex["specimens"]:
        lines.extend(
            [
                f"### {specimen['name']}",
                "",
                f"- Family: {str(specimen['attack_family']).replace('_', ' ')}",
                f"- Temperament: {specimen['temperament']}",
                f"- Sightings: {specimen['sightings']}",
                f"- Proven bites: {specimen['proven_sightings']}",
                f"- Highest score: {specimen['highest_score']}",
                f"- Tells: {', '.join(specimen['tells'])}",
                f"- Containment: {specimen['containment']}",
                "",
            ]
        )

    lines.extend(
        [
            "## Trap Ledger",
            "",
            "| Trap | Survived | Severity | Risk | Specimens | Prompt |",
            "|---:|---|---|---:|---|---|",
        ]
    )
    for row in rows:
        prompt = str(row["prompt_excerpt"]).replace("|", "\\|")
        specimens = str(row["specimens"]).replace("|", "\\|")
        lines.append(
            f"| {row['trap']} | {row['survived']} | {row['severity']} | {row['risk_score']} | {specimens} | {prompt} |"
        )
    lines.append("")
    return "\n".join(lines)


def build_offline_proof(*, source_label: str) -> str:
    return "\n".join(
        [
            "HONEYPOT MED OFFLINE PROOF",
            "",
            "This artifact was generated by local deterministic code in the open-source Honeypot Med repository.",
            "Default challenge, share, export, and lab artifact generation do not require API keys.",
            "No model API call, paid hosted service, or remote enrichment is required for the free path.",
            "",
            f"Source: {source_label}",
            f"Generated: {datetime.now(timezone.utc).isoformat()}",
            "",
        ]
    )


def write_lab_artifacts(report: dict, outdir: str, *, source_label: str, title: str) -> dict:
    """Write offline Trap Lab artifacts next to other bundle outputs."""
    target = Path(outdir)
    target.mkdir(parents=True, exist_ok=True)

    codex_path = target / "specimen-codex.json"
    ledger_json_path = target / "trap-ledger.json"
    ledger_csv_path = target / "trap-ledger.csv"
    field_guide_path = target / "field-guide.md"
    offline_proof_path = target / "offline-proof.txt"
    proof_dossier_html_path = target / "proof-dossier.html"
    proof_dossier_pdf_path = target / "offline-proof.pdf"
    ui_mockup_path = target / "ui-mockup.html"
    ledger = build_trap_ledger(report)

    codex_path.write_text(json.dumps(build_specimen_codex(report), indent=2) + "\n", encoding="utf-8")
    ledger_json_path.write_text(json.dumps(ledger, indent=2) + "\n", encoding="utf-8")
    ledger_csv_path.write_text(build_trap_ledger_csv(report), encoding="utf-8")
    field_guide_path.write_text(
        build_field_guide_markdown(report, source_label=source_label, title=title),
        encoding="utf-8",
    )
    offline_proof_path.write_text(build_offline_proof(source_label=source_label), encoding="utf-8")
    proof_dossier_html_path.write_text(
        build_proof_dossier_html(report, ledger, source_label=source_label, title=title).rstrip() + "\n",
        encoding="utf-8",
    )
    proof_dossier_pdf_path.write_bytes(
        build_offline_proof_pdf(report, ledger, source_label=source_label, title=title)
    )
    ui_mockup_path.write_text(
        build_ui_mockup_html(report, ledger, source_label=source_label, title=title).rstrip() + "\n",
        encoding="utf-8",
    )
    inquiry_artifacts = write_inquiry_artifacts(
        report,
        str(target),
        source_label=source_label,
        title=title,
    )

    return {
        "specimen_codex": str(codex_path),
        "trap_ledger_json": str(ledger_json_path),
        "trap_ledger_csv": str(ledger_csv_path),
        "field_guide": str(field_guide_path),
        "offline_proof": str(offline_proof_path),
        "proof_dossier_html": str(proof_dossier_html_path),
        "proof_dossier_pdf": str(proof_dossier_pdf_path),
        "ui_mockup": str(ui_mockup_path),
        **inquiry_artifacts,
    }
