"""Local observability exports for traces and collector fixtures."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _jsonl(rows: list[dict]) -> str:
    return "".join(json.dumps(row, sort_keys=True) + "\n" for row in rows)


def build_openinference_rows(report: dict, *, source_label: str) -> list[dict]:
    rows = []
    for index, event in enumerate(report.get("events", []), start=1):
        trace_id = f"honeypot-med-{index:032d}"[-32:]
        rows.append(
            {
                "trace_id": trace_id,
                "span_id": f"{index:016d}",
                "parent_span_id": None,
                "name": f"honeypot_med.trap.{index:03d}",
                "kind": "CHAIN",
                "start_time": _now(),
                "end_time": _now(),
                "attributes": {
                    "input.value": str(event.get("prompt", "")),
                    "output.value": str(event.get("response") or event.get("model_output") or ""),
                    "metadata.source": source_label,
                    "metadata.severity": str(event.get("severity", "low")),
                    "metadata.risk_score": int(event.get("risk_score", 0)),
                    "metadata.finding_count": int(event.get("finding_count", 0)),
                    "metadata.proven_count": int(event.get("proven_count", 0)),
                },
            }
        )
    return rows


def build_langsmith_rows(report: dict, *, source_label: str, project_name: str = "honeypot-med") -> list[dict]:
    rows = []
    for index, event in enumerate(report.get("events", []), start=1):
        rows.append(
            {
                "id": f"honeypot-med-run-{index:03d}",
                "name": f"trap-{index:03d}",
                "run_type": "chain",
                "project_name": project_name,
                "start_time": _now(),
                "end_time": _now(),
                "inputs": {"prompt": str(event.get("prompt", ""))},
                "outputs": {"response": str(event.get("response") or event.get("model_output") or "")},
                "extra": {
                    "source": source_label,
                    "severity": str(event.get("severity", "low")),
                    "risk_score": int(event.get("risk_score", 0)),
                    "finding_count": int(event.get("finding_count", 0)),
                    "proven_count": int(event.get("proven_count", 0)),
                    "honeypot_med": True,
                },
            }
        )
    return rows


def build_otel_collector_config(*, logs_path: str = "otel-logs.json") -> str:
    return "\n".join(
        [
            "# Generated by Honeypot Med. Local collector fixture; edit endpoints before production use.",
            "receivers:",
            "  filelog/honeypot_med:",
            f"    include: [{logs_path}]",
            "    start_at: beginning",
            "exporters:",
            "  debug:",
            "    verbosity: detailed",
            "service:",
            "  pipelines:",
            "    logs:",
            "      receivers: [filelog/honeypot_med]",
            "      exporters: [debug]",
            "",
        ]
    )


def write_observability_artifacts(report: dict, outdir: str, *, source_label: str) -> dict:
    target = Path(outdir)
    target.mkdir(parents=True, exist_ok=True)
    openinference_path = target / "openinference-traces.jsonl"
    langsmith_path = target / "langsmith-runs.jsonl"
    collector_path = target / "otel-collector.yaml"

    openinference_path.write_text(_jsonl(build_openinference_rows(report, source_label=source_label)), encoding="utf-8")
    langsmith_path.write_text(_jsonl(build_langsmith_rows(report, source_label=source_label)), encoding="utf-8")
    collector_path.write_text(build_otel_collector_config(), encoding="utf-8")

    return {
        "openinference_traces": str(openinference_path),
        "langsmith_runs": str(langsmith_path),
        "otel_collector_config": str(collector_path),
    }
